language: python
python: 
  - "2.7"
# install dependencies
install:
  - pip install -r app/requirements.txt

stages:
  - unittest
jobs:
  include:
    - stage: unittest
      script: cd app;python -m unittest tests.test_helloworld
